name: Lint Checks

on:
  push:
    branches: [ main, refactor/atomic-files ] # Adjust branches as needed
  pull_request:
    branches: [ main ] # Adjust branches as needed

jobs:
  check-file-length:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Make script executable
        run: chmod +x ./scripts/check-length.sh

      - name: Check file lengths (max 250 lines)
        run: ./scripts/check-length.sh 